const menu = [
  {
    id: 1,
    title: 'wireless headphones',
    category: 'electronics',
    price: 79.99,
    img: '/images/item-1.jpeg',
    desc: `High-quality Bluetooth headphones with noise cancellation and up to 30 hours of battery life.`,
  },
  {
    id: 2,
    title: 'leather backpack',
    category: 'fashion',
    price: 59.99,
    img: '/images/item-2.jpeg',
    desc: `Stylish and durable leather backpack with multiple compartments, perfect for daily use or travel.`,
  },
  {
    id: 3,
    title: 'smartwatch pro',
    category: 'electronics',
    price: 199.99,
    img: '/images/item-3.jpeg',
    desc: `Feature-packed smartwatch with heart rate monitoring, GPS tracking, and waterproof design.`,
  },
  {
    id: 4,
    title: 'aromatherapy candle set',
    category: 'home decor',
    price: 24.99,
    img: '/images/item-4.jpeg',
    desc: `A set of three scented candles with calming lavender, refreshing citrus, and warm vanilla fragrances.`,
  },
  {
    id: 5,
    title: 'ergonomic office chair',
    category: 'furniture',
    price: 129.99,
    img: '/images/item-5.jpeg',
    desc: `Comfortable office chair with adjustable lumbar support, breathable mesh, and 360-degree swivel.`,
  },
  {
    id: 6,
    title: 'wireless charging pad',
    category: 'electronics',
    price: 29.99,
    img: '/images/item-6.jpeg',
    desc: `Fast-charging wireless pad compatible with most smartphones and smartwatches.`,
  },
  {
    id: 7,
    title: 'stainless steel water bottle',
    category: 'accessories',
    price: 19.99,
    img: '/images/item-7.jpeg',
    desc: `Insulated stainless steel bottle that keeps drinks cold for 24 hours and hot for 12 hours.`,
  },
  {
    id: 8,
    title: 'minimalist wall clock',
    category: 'home decor',
    price: 39.99,
    img: '/images/item-8.jpeg',
    desc: `Sleek and modern wall clock with a silent mechanism and a timeless design.`,
  },
  {
    id: 9,
    title: 'virtual reality headset',
    category: 'electronics',
    price: 299.99,
    img: '/images/item-9.jpeg',
    desc: `Immersive VR headset with high-resolution display and advanced motion tracking.`,
  },
];

export default menu;
